events {}

http {

    upstream portfolio {
        server portfolio:80;
    }

    upstream java {
        server java:8080;
    }

    server {

        listen 80;

        server_name _;

        location / {
            proxy_pass http://portfolio;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /java/ {
            proxy_pass http://java/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
